# dillo
# Autogenerated from man page /usr/share/man/man1/dillo.1.gz
complete -c dillo -s f -l fullwindow --description 'Start in full window mode: hide address bar, navigation buttons, menu, and st…'
complete -c dillo -s g -o geometry --description 'Set initial window position where GEO is WxH[{+-}X{+-}Y].'
complete -c dillo -s h -l help --description 'Display this help text and exit.'
complete -c dillo -s l -l local --description 'Don\'t load images or stylesheets, or follow redirections, for these FILEs or …'
complete -c dillo -s v -l version --description 'Display version info and exit.'
complete -c dillo -s x -l xid --description 'Open first Dillo window in an existing window whose window ID is XID.'

