# display
# Autogenerated from man page /usr/share/man/man1/display.1.gz
complete -c display -s h -l help --description 'Show help options.'
complete -c display -l help-all --description 'Show all help options.'
complete -c display -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c display -s v -l version --description 'Print version information and exit.'
complete -c display -l slideshow --description 'Start slideshow.'
complete -c display -l display --description 'X display to use AUTHOR gpicview was written by PCMan (Hong Jen Yee) <pcman.'

