# dmypy-recheck
# Autogenerated from man page /usr/share/man/man1/dmypy-recheck.1.gz
complete -c dmypy-recheck -s h -l help --description 'Show a help message and exit.'
complete -c dmypy-recheck -l status-file --description 'Status file to retrieve daemon details to.'
complete -c dmypy-recheck -s V -l version --description 'Show programâs version number and exit.'
complete -c dmypy-recheck -l timeout --description 'stop.'
complete -c dmypy-recheck -s v -l verbose --description 'Print detailed status.'
complete -c dmypy-recheck -l junit-xml --description 'Write junit. xml to the given file.'
complete -c dmypy-recheck -l perf-stats-file --description 'Write telemetry information to the given file.'
complete -c dmypy-recheck -l log-file --description 'Direct daemon stdout/stderr to FILE.'

