# dmypy-status
# Autogenerated from man page /usr/share/man/man1/dmypy-status.1.gz
complete -c dmypy-status -s h -l help --description 'Show a help message and exit.'
complete -c dmypy-status -l status-file --description 'Status file to retrieve daemon details to.'
complete -c dmypy-status -s V -l version --description 'Show programâs version number and exit.'
complete -c dmypy-status -l timeout --description 'stop.'
complete -c dmypy-status -s v -l verbose --description 'Print detailed status.'
complete -c dmypy-status -l junit-xml --description 'Write junit. xml to the given file.'
complete -c dmypy-status -l perf-stats-file --description 'Write telemetry information to the given file.'
complete -c dmypy-status -l log-file --description 'Direct daemon stdout/stderr to FILE.'

