# dmypy-hang
# Autogenerated from man page /usr/share/man/man1/dmypy-hang.1.gz
complete -c dmypy-hang -s h -l help --description 'Show a help message and exit.'
complete -c dmypy-hang -l status-file --description 'Status file to retrieve daemon details to.'
complete -c dmypy-hang -s V -l version --description 'Show programâs version number and exit.'
complete -c dmypy-hang -l timeout --description 'stop.'
complete -c dmypy-hang -s v -l verbose --description 'Print detailed status.'
complete -c dmypy-hang -l junit-xml --description 'Write junit. xml to the given file.'
complete -c dmypy-hang -l perf-stats-file --description 'Write telemetry information to the given file.'
complete -c dmypy-hang -l log-file --description 'Direct daemon stdout/stderr to FILE.'

