# dtmerge
# Autogenerated from man page /usr/share/man/man1/dtmerge.1.gz
complete -c dtmerge -s d --description 'Show debug output during operation.'
complete -c dtmerge -s h --description 'Displays help on the application.  EXAMPLES dtmerge /boot/bcm2711-rpi-4-b.'

