# dtoverlay
# Autogenerated from man page /usr/share/man/man1/dtoverlay.1.gz
complete -c dtoverlay -s a --description 'Lists all defined device-tree overlays, placing a "*" next to those that are …'
complete -c dtoverlay -s d --description 'Specifies an alternate location path from which to load overlays.'
complete -c dtoverlay -s D --description 'Dry-run; prepares the specified overlay but doesn\'t apply it.'
complete -c dtoverlay -s h --description 'If given without  overlay or  param displays help on the application overall.'
complete -c dtoverlay -s l --description 'Lists all currently loaded device-tree overlays, in the order they were loade…'
complete -c dtoverlay -s p --description 'Override the platform\'s "compatible" string, normally read from "/proc/device…'
complete -c dtoverlay -s r --description 'Remove overlay.'
complete -c dtoverlay -s R --description 'Remove the specified overlay, and all subsequent overlays that were loaded af…'
complete -c dtoverlay -s v --description 'Verbose operation; the utility will produce more output.'

