# exfatlabel
# Autogenerated from man page /usr/share/man/man8/exfatlabel.8.gz
complete -c exfatlabel -s i --description 'Switch to volume serial mode.'
complete -c exfatlabel -l volume-serial --description 'mode.'
complete -c exfatlabel -s V --description 'Prints the version number and exits.'

