# rpi-eeprom-config
# Autogenerated from man page /usr/share/man/man1/rpi-eeprom-config.1.gz
complete -c rpi-eeprom-config -s d -s p --description '[eeprom] . PP Bootloader EEPROM configuration tool for the Raspberry Pi 4.'
complete -c rpi-eeprom-config -s h -l help --description 'show this help message and exit.'
complete -c rpi-eeprom-config -s a -l apply --description 'Updates the bootloader to the given config plus latest available EEPROM relea…'
complete -c rpi-eeprom-config -s c -l config --description 'Name of bootloader configuration file.'
complete -c rpi-eeprom-config -s e -l edit --description 'Edit the current EEPROM config.'
complete -c rpi-eeprom-config -s o -l out --description 'Name of output file.'
complete -c rpi-eeprom-config -l digest --description 'Signed boot only.  The name of the .'
complete -c rpi-eeprom-config -l pubkey --description 'Signed boot only.  The name of the RSA public key file to store in the EEPROM.'
complete -c rpi-eeprom-config -s x -l extract --description 'Extract the modifiable files (boot. conf, pubkey, signature).'

