# stubgen
# Autogenerated from man page /usr/share/man/man1/stubgen.1.gz
complete -c stubgen -s m -l module --description 'Generate a stub file for the given module.'
complete -c stubgen -s p -l package --description 'Generate stubs for the given package.'
complete -c stubgen -l no-import --description 'Don\\(aqt try to import modules.'
complete -c stubgen -l parse-only --description 'Don\\(aqt perform semantic analysis of source files.'
complete -c stubgen -l doc-dir --description 'Try to infer better signatures by parsing . rst documentation in PATH.'
complete -c stubgen -s h -l help --description 'Show help message and exit.'
complete -c stubgen -l py2 --description 'Run stubgen in Python 2 mode (the default is Python 3 mode).'
complete -c stubgen -l ignore-errors --description 'If an exception was raised during stub generation, continue to process any re…'
complete -c stubgen -l include-private --description 'Include definitions that are considered private in stubs (with names such as …'
complete -c stubgen -l export-less --description 'Don\\(aqt export all names imported from other modules within the same package.'
complete -c stubgen -l search-path --description 'Specify module search directories, separated by colons (only used if --no-imp…'
complete -c stubgen -l python-executable --description 'Use Python interpreter at PATH for importing modules and runtime introspectio…'
complete -c stubgen -s o -l output --description 'Change the output directory.  By default the stubs are written in the .'
complete -c stubgen -s v -l verbose --description 'Produce more verbose output.'
complete -c stubgen -s q -l quiet --description 'Produce less verbose output.'

