# vcgencmd
# Autogenerated from man page /usr/share/man/man1/vcgencmd.1.gz
complete -c vcgencmd -s t --description 'Time how long the command takes to complete .'
complete -c vcgencmd -s h -l help --description 'Show this information COMMANDS To get a list of all the commands that vcgencm…'
complete -c vcgencmd -s 1 --description 'Problem with VHCI.'
complete -c vcgencmd -s 2 --description 'VideoCore returned an error SEE ALSO [DOCS] https://www. raspberrypi.'

