# vnclicense
# Autogenerated from man page /usr/share/man/man1/vnclicense.1.gz
complete -c vnclicense -o add --description 'Apply the offline license FILE, overwriting any existing license.'
complete -c vnclicense -o remove --description 'Remove the current offline license.   Must be run as root.'
complete -c vnclicense -o list --description 'Print information about the current offline license.'
complete -c vnclicense -o info --description 'Print information about the given offline license FILE.'
complete -c vnclicense -o check --description 'Check how many instances of VNC Server are running on this computer.'
complete -c vnclicense -o reload --description 'Reload the offline license and other settings for all running instances of VN…'

