# vncpasswd
# Autogenerated from man page /usr/share/man/man1/vncpasswd.1.gz
complete -c vncpasswd -o service --description 'VNC Server in Service Mode.  Note elevated privileges are required.'
complete -c vncpasswd -o user --description 'VNC Server in User Mode.'
complete -c vncpasswd -o virtual --description 'VNC Server in Virtual Mode.'

