# vncserver-x11-serviced
# Autogenerated from man page /usr/share/man/man1/vncserver-x11-serviced.1.gz
complete -c vncserver-x11-serviced -o fg --description 'Runs in the foreground (not as a daemon), which may be useful for troubleshoo…'

