# vncserver-virtuald
# Autogenerated from man page /usr/share/man/man1/vncserver-virtuald.1.gz
complete -c vncserver-virtuald -o fg --description 'Runs in the foreground (not as a daemon), which may be useful for troubleshoo…'
complete -c vncserver-virtuald -o help --description 'it to the command executing the binary in the appropriate init script; see %S…'

