# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
complete -c x-terminal-emulator -s e -l command -l command --description 'This option specifies the program (and its command line arguments) to be run …'
complete -c x-terminal-emulator -l geometry --description 'Set the terminal\\*(Aqs size in characters and lines.'
complete -c x-terminal-emulator -s l -l loginshell --description 'Executes login shell.'
complete -c x-terminal-emulator -s t -l title -l tabs --description 'Set the terminal\\*(Aqs title.  Use comma for multiple tabs.'
complete -c x-terminal-emulator -l working-directory --description 'Set the terminal\\*(Aqs working directory.'

