# Xvnc
# Autogenerated from man page /usr/share/man/man1/Xvnc.1.gz
complete -c Xvnc -o connect --description 'Establishes a reverse connection to a Listening VNC Viewer on HOST at PORT (5…'
complete -c Xvnc -o disconnect --description 'Disconnects all VNC Viewers.'
complete -c Xvnc -o generatekeys --description 'Generates and stores an RSA private key; force overwrites an existing key.'
complete -c Xvnc -o reload --description 'Reloads offline license and configuration files.'
complete -c Xvnc -o stop --description 'Stops VNC Server, disconnecting all VNC Viewers, and destroying the virtual d…'
complete -c Xvnc -o showexistingstatus --description 'Causes the VNC Server status dialog to be displayed to connected VNC Viewers.'

