// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "4314995b-2004-4e1d-8da4-09c86dc063c6");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1715184640);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1715185255);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1715185173);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{d3a786a0-c1fd-4407-9708-d66429a9e0f3}");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1715184586);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8928e471-a71b-445a-8307-c587a39b4af7}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1715185154);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1715185252483");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1715187041483");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1715185193534");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1715206793534");
user_pref("browser.search.region", "JP");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230912014407");
user_pref("browser.startup.homepage_override.mstone", "102.15.1");
user_pref("browser.startup.lastColdStartupCheck", 1715185151);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1715185171698");
user_pref("distribution.iniFile.exists.appversion", "102.15.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "JP");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230912014407");
user_pref("extensions.lastAppVersion", "102.15.1");
user_pref("extensions.lastPlatformVersion", "102.15.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8dd7c94c-8740-4e79-933f-9038eb73a633\",\"formautofill@mozilla.org\":\"42faac1d-a378-4578-b2d9-962d8844440e\",\"pictureinpicture@mozilla.org\":\"cc7aa81d-c158-45df-8ace-2188d8b17404\",\"screenshots@mozilla.org\":\"c1877cf2-6b53-4151-936e-1142732a8fd9\",\"webcompat-reporter@mozilla.org\":\"3d386aca-1393-4799-a8e7-bd217857e1f7\",\"webcompat@mozilla.org\":\"13f266a5-2466-483b-a672-c7edc3662cd6\",\"default-theme@mozilla.org\":\"f6582124-6e92-4db6-bdf1-967a4eabf73b\",\"addons-search-detection@mozilla.com\":\"f633ae7d-efe5-45d2-a46f-83530a78b119\",\"google@search.mozilla.org\":\"c9830e57-3b8e-4a94-9898-73847d8224bd\",\"wikipedia@search.mozilla.org\":\"c8668c43-3ef2-49a2-a317-7f83a281543e\",\"bing@search.mozilla.org\":\"3041d46f-81ee-40a6-b73b-f3c5b047c0bb\",\"ddg@search.mozilla.org\":\"ab87aa58-2c6c-4a6f-a07c-7c7d45159edd\",\"amazon@search.mozilla.org\":\"d8d1c5b1-f221-489f-b952-35f7d139f877\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2f44042c-6af6-4ae4-841a-fe99cd83a59b");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1715185131);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230912014407");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
